import * as cdk from "aws-cdk-lib";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as iam from "aws-cdk-lib/aws-iam";
import * as kms from "aws-cdk-lib/aws-kms";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as logs from "aws-cdk-lib/aws-logs";
import * as pipes from "aws-cdk-lib/aws-pipes";
import { NagSuppressions } from "cdk-nag";
import { Construct } from "constructs";

export interface EventBridgePipeConstructProps {
  table: dynamodb.Table;
  notificationBridgeLambda: lambda.Function;
  encryptionKey: kms.IKey;
}

/**
 * EventBridge Pipe: DynamoDB Stream → Notification Bridge Lambda.
 *
 * Filters for task status changes (completed/failed) and invokes the
 * notification bridge to fan out WebSocket updates to subscribed clients.
 */
export class EventBridgePipeConstruct extends Construct {
  constructor(scope: Construct, id: string, props: EventBridgePipeConstructProps) {
    super(scope, id);

    // IAM role for the pipe
    const pipeRole = new iam.Role(this, "PipeRole", {
      assumedBy: new iam.ServicePrincipal("pipes.amazonaws.com"),
      description: "Role for AI-Deploy task notification EventBridge Pipe",
    });

    // Grant stream read on the DynamoDB table
    props.table.grantStreamRead(pipeRole);

    // Grant invoke on the notification bridge Lambda
    props.notificationBridgeLambda.grantInvoke(pipeRole);

    // Grant KMS decrypt so the pipe can read encrypted stream records
    props.encryptionKey.grantDecrypt(pipeRole);

    // Log group for pipe error logging
    const pipeLogGroup = new logs.LogGroup(this, "PipeLogGroup", {
      logGroupName: "/ai-deploy/pipes/task-notification",
      retention: logs.RetentionDays.SIX_MONTHS,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      encryptionKey: props.encryptionKey,
    });

    pipeLogGroup.grantWrite(pipeRole);

    // EventBridge Pipe (L1 CfnPipe)
    // Uses REQUEST_RESPONSE so the pipe tracks invocation success and retries
    // on transient Lambda failures (via DynamoDB stream retry behavior).
    new pipes.CfnPipe(this, "TaskNotificationPipe", {
      name: "ai-deploy-task-notification",
      roleArn: pipeRole.roleArn,
      source: props.table.tableStreamArn!,
      sourceParameters: {
        dynamoDbStreamParameters: {
          startingPosition: "LATEST",
          batchSize: 10,
          maximumBatchingWindowInSeconds: 5,
          maximumRetryAttempts: 3,
          onPartialBatchItemFailure: "AUTOMATIC_BISECT",
        },
        filterCriteria: {
          filters: [
            {
              pattern: JSON.stringify({
                eventName: ["MODIFY"],
                dynamodb: {
                  Keys: {
                    sk: { S: [{ prefix: "TASK#" }, { prefix: "IAC_TASK#" }, { prefix: "DOCS_TASK#" }] },
                  },
                  NewImage: {
                    status: { S: ["completed", "failed"] },
                  },
                },
              }),
            },
          ],
        },
      },
      target: props.notificationBridgeLambda.functionArn,
      targetParameters: {
        lambdaFunctionParameters: {
          invocationType: "REQUEST_RESPONSE",
        },
      },
      logConfiguration: {
        cloudwatchLogsLogDestination: {
          logGroupArn: pipeLogGroup.logGroupArn,
        },
        level: "ERROR",
      },
    });

    // cdk-nag suppressions for the pipe IAM role
    NagSuppressions.addResourceSuppressions(
      pipeRole,
      [
        {
          id: "AwsSolutions-IAM5",
          reason:
            "DynamoDB stream wildcards are auto-generated by CDK grantStreamRead(). " +
            "Lambda invoke wildcard on function ARN is auto-generated by CDK grantInvoke(). " +
            "KMS decrypt Resource::* is required for reading encrypted DynamoDB stream records. " +
            "CloudWatch Logs wildcards are auto-generated by CDK log group grantWrite().",
          appliesTo: [
            "Resource::*",
            {
              regex: "/^Resource::<.+\\.Arn>:\\*$/",
            },
          ],
        },
      ],
      true,
    );
  }
}
