"""ResourcePlan models — structured LLM output for CFN assembly.

The LLM generates these models as structured JSON via Strands
``structured_output_model``.  Python code then converts them to valid
CloudFormation YAML via the CFN Assembler (``cfn_assembler.py``).

Intrinsic functions are represented as plain dicts with lowercase keys:

    {"ref": "VPC"}                              -> !Ref VPC
    {"sub": "${AWS::StackName}-vpc"}            -> !Sub "${AWS::StackName}-vpc"
    {"get_att": ["Resource", "Attribute"]}      -> !GetAtt Resource.Attribute
    {"select": [0, {"get_azs": ""}]}           -> !Select [0, !GetAZs ""]
    {"join": [",", [{"ref": "A"}, {"ref": "B"}]]} -> !Join [",", [!Ref A, !Ref B]]
    {"find_in_map": ["Map", "Key1", "Key2"]}   -> !FindInMap [Map, Key1, Key2]
    {"if": ["Cond", "TrueVal", "FalseVal"]}    -> !If [Cond, TrueVal, FalseVal]
    {"base64": {"ref": "UserData"}}            -> !Base64 !Ref UserData
    {"get_azs": ""}                            -> !GetAZs ""
    {"cidr": ["10.0.0.0/16", 6, 8]}           -> !Cidr [10.0.0.0/16, 6, 8]
    {"equals": ["a", "b"]}                     -> !Equals [a, b]
    {"not": [{"equals": ["a", "b"]}]}          -> !Not [!Equals [a, b]]
    {"and": [cond1, cond2]}                    -> !And [cond1, cond2]
    {"or": [cond1, cond2]}                     -> !Or [cond1, cond2]
    {"condition": "MyCondition"}               -> !Condition MyCondition
    {"import_value": "SharedStack-VPCID"}      -> !ImportValue SharedStack-VPCID
    {"split": [",", {"ref": "Param"}]}         -> !Split [",", !Ref Param]
"""

from typing import Any

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# CloudFormation section models
# ---------------------------------------------------------------------------


class CfnParameter(BaseModel):
    """A CloudFormation Parameter."""

    logical_id: str = Field(description="Parameter logical name (e.g., 'VpcCidr')")
    type: str = Field(
        description="CFN parameter type: String, Number, "
        "CommaDelimitedList, AWS::EC2::Image::Id, etc."
    )
    default: str | None = None
    description: str = ""
    allowed_values: list[str] | None = None
    constraint_description: str | None = None
    no_echo: bool = False


class CfnResource(BaseModel):
    """A single CloudFormation Resource."""

    logical_id: str = Field(description="Resource logical name (e.g., 'InspectionVPC')")
    type: str = Field(description="AWS resource type (e.g., 'AWS::EC2::VPC')")
    properties: dict[str, Any] = Field(
        default_factory=dict,
        description="Resource properties. Values can be plain strings/numbers/lists "
        "or intrinsic function dicts like {'ref': 'VPC'}.",
    )
    depends_on: list[str] | None = None
    condition: str | None = None
    metadata: dict[str, Any] | None = None

    @field_validator("type")
    @classmethod
    def _validate_type_format(cls, v: str) -> str:
        if not v.startswith("AWS::") and not v.startswith("Custom::"):
            raise ValueError(
                f"Resource type must start with 'AWS::' or 'Custom::': {v}"
            )
        return v


class CfnOutput(BaseModel):
    """A CloudFormation Output."""

    logical_id: str
    value: Any  # Can be plain string or intrinsic function dict
    description: str = ""
    export_name: Any | None = None  # Can use intrinsic functions
    condition: str | None = None


class CfnMapping(BaseModel):
    """A CloudFormation Mapping."""

    logical_id: str
    mapping: dict[str, dict[str, Any]]


class CfnCondition(BaseModel):
    """A CloudFormation Condition."""

    logical_id: str
    condition: dict[str, Any]  # Intrinsic function dict


# ---------------------------------------------------------------------------
# Top-level plan (Path 3: GENERATE)
# ---------------------------------------------------------------------------


class ResourcePlan(BaseModel):
    """Structured resource plan generated by the LLM.

    Replaces raw YAML generation. The CFN Assembler converts this to
    valid CloudFormation YAML deterministically.
    """

    description: str = ""
    parameters: list[CfnParameter] = Field(default_factory=list)
    mappings: list[CfnMapping] = Field(default_factory=list)
    conditions: list[CfnCondition] = Field(default_factory=list)
    resources: list[CfnResource] = Field(min_length=1)
    outputs: list[CfnOutput] = Field(default_factory=list)

    @field_validator("resources")
    @classmethod
    def _no_duplicate_logical_ids(cls, v: list[CfnResource]) -> list[CfnResource]:
        ids = [r.logical_id for r in v]
        dupes = {lid for lid in ids if ids.count(lid) > 1}
        if dupes:
            raise ValueError(f"Duplicate resource logical IDs: {dupes}")
        return v


# ---------------------------------------------------------------------------
# Snippet assembly plan (Path 2: COMPOSE)
# ---------------------------------------------------------------------------


class SnippetWiring(BaseModel):
    """How to wire one cross-snippet reference."""

    source_snippet: str = Field(description="Which snippet provides the value")
    source_logical_id: str = Field(description="Resource logical ID in the source snippet")
    source_attribute: str | None = Field(
        default=None,
        description="If GetAtt, the attribute name (e.g., 'VpcId'). None means Ref.",
    )
    target_snippet: str = Field(description="Which snippet consumes the value")
    target_resource_logical_id: str = Field(
        description="Resource logical ID in the target snippet"
    )
    target_property_path: str = Field(
        description="Dot-delimited path to the property to replace "
        "(e.g., 'VpcId' or 'SecurityGroupIds.0')"
    )


class SnippetAssemblyPlan(BaseModel):
    """LLM-generated plan for assembling snippets (Path 2: COMPOSE).

    The LLM analyses parsed snippet summaries and produces a wiring plan.
    Code executes the plan deterministically to merge snippets into a
    single CloudFormation template.
    """

    wiring: list[SnippetWiring] = Field(default_factory=list)
    parameter_dedup_keep: dict[str, str] = Field(
        default_factory=dict,
        description="For duplicate parameter names across snippets, which snippet's "
        "definition to keep. Maps param_name -> snippet_name.",
    )
    output_selection: list[str] = Field(
        default_factory=list,
        description="Output logical IDs to include in the final template. "
        "Empty list means include all outputs.",
    )
    resource_renames: dict[str, str] = Field(
        default_factory=dict,
        description="Logical ID renames to avoid conflicts across snippets. "
        "Maps old_id -> new_id.",
    )
