"""Catalog lock file schema — the deterministic contract for product deployment interviews.

catalog.lock.yaml is auto-generated by the Catalog Discovery Agent from the Knowledge Base,
then reviewed and committed. At runtime it provides:
- What products exist
- What fields each product needs (blocking vs optional)
- What deployment patterns are available
- Appliance configuration (interfaces, instance types)
- KB search templates and guardrails

The CatalogLoader reads this once at startup and provides typed access everywhere.
"""

from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Field definitions — the building blocks of interview schemas
# ---------------------------------------------------------------------------


class FieldDefinition(BaseModel):
    """A single interview field with type info and optional constraints."""

    name: str
    type: str = Field(description="Python type hint: str, int, float, bool, enum, list_str, object")
    description: str = ""
    options: list[str] | None = Field(default=None, description="Valid values for enum types")
    unit: str | None = Field(default=None, description="Unit of measurement (e.g., 'Mbps')")
    default: Any = None
    doc_type: str = Field(default="configuration", description="KB document_type for targeted search")
    fields: list["FieldDefinition"] | None = Field(
        default=None, description="Sub-fields for object types"
    )


# ---------------------------------------------------------------------------
# Use case schema
# ---------------------------------------------------------------------------


class UseCaseSchema(BaseModel):
    """A product use case with its required/optional interview fields."""

    value: str = Field(description="Machine key (e.g., 'sd-wan')")
    label: str = Field(description="Human-readable label (e.g., 'SD-WAN')")
    required_fields: list[FieldDefinition] = Field(default_factory=list)
    optional_fields: list[FieldDefinition] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Interview schema — base fields + use-case-specific fields
# ---------------------------------------------------------------------------


class BaseFieldsSchema(BaseModel):
    """Base interview fields that apply regardless of use case."""

    blocking: list[FieldDefinition] = Field(default_factory=list)
    soft: list[FieldDefinition] = Field(default_factory=list)


class InterviewSchema(BaseModel):
    """Complete interview definition for a product."""

    use_cases: list[UseCaseSchema] = Field(default_factory=list)
    base_fields: BaseFieldsSchema = Field(default_factory=BaseFieldsSchema)


# ---------------------------------------------------------------------------
# Appliance configuration
# ---------------------------------------------------------------------------


class InterfaceRoleConfig(BaseModel):
    """Configuration for an appliance network interface role."""

    source_dest_check: bool = True
    subnet_role: str
    description: str = ""


class ApplianceConfig(BaseModel):
    """Hardware/network appliance configuration from KB."""

    interface_naming: str = Field(default="port{n}", description="Interface naming pattern")
    approved_instance_types: list[str] = Field(default_factory=list)
    interface_roles: dict[str, InterfaceRoleConfig] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Deployment patterns
# ---------------------------------------------------------------------------


class PatternConfig(BaseModel):
    """A deployment pattern (e.g., single-instance, ha-active-passive)."""

    name: str
    aliases: list[str] = Field(default_factory=list)
    layers: list[str] = Field(default_factory=list)
    description: str = ""


# ---------------------------------------------------------------------------
# Knowledge Base configuration
# ---------------------------------------------------------------------------


class KBSearchConfig(BaseModel):
    """KB search settings from the lock file."""

    search_template: str = Field(
        default="{product_name} {use_case} deployment AWS",
        description="Template for KB queries — variables substituted at runtime",
    )
    document_types: list[str] = Field(
        default_factory=lambda: ["architecture", "sizing", "configuration", "components", "best-practices"]
    )


# ---------------------------------------------------------------------------
# Guardrails
# ---------------------------------------------------------------------------


class GuardrailsConfig(BaseModel):
    """Content guardrails for the deployment assistant."""

    focus_topics: list[str] = Field(default_factory=list)
    denied_topics: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Product — top-level entity in the catalog
# ---------------------------------------------------------------------------


class CatalogProduct(BaseModel):
    """A single product in the catalog with full deployment schema."""

    id: str
    name: str
    vendor: str
    category: str = ""
    kb_doc_prefix: str = Field(default="", description="S3/local path prefix for this product's docs")

    interview: InterviewSchema = Field(default_factory=InterviewSchema)
    appliance: ApplianceConfig = Field(default_factory=ApplianceConfig)
    patterns: list[PatternConfig] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Root lock file
# ---------------------------------------------------------------------------


class CatalogLock(BaseModel):
    """Root schema for catalog.lock.yaml — the full deterministic contract."""

    schema_version: int = 1
    products: list[CatalogProduct] = Field(default_factory=list)
    knowledge_base: KBSearchConfig = Field(default_factory=KBSearchConfig)
    guardrails: GuardrailsConfig = Field(default_factory=GuardrailsConfig)
